#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Bot

#include "Basic.hpp"

#include "BP_Bot_classes.hpp"
#include "BP_Bot_parameters.hpp"


namespace SDK
{

// Function BP_Bot.BP_bot_C.ExecuteUbergraph_BP_bot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_bot_C::ExecuteUbergraph_BP_bot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_bot_C", "ExecuteUbergraph_BP_bot");

	Params::BP_bot_C_ExecuteUbergraph_BP_bot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Bot.BP_bot_C.Walk
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Goal                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Goal2                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_bot_C::Walk(const class AActor* Goal, const class AActor* Goal2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_bot_C", "Walk");

	Params::BP_bot_C_Walk Parms{};

	Parms.Goal = Goal;
	Parms.Goal2 = Goal2;

	UObject::ProcessEvent(Func, &Parms);
}

}

