#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DLSSApply

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_CustomSettingsApplyClass_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DLSSApply.BP_DLSSApply_C
// 0x0028 (0x0058 - 0x0030)
class UBP_DLSSApply_C final : public UBP_CustomSettingsApplyClass_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_DLSSApply_C;                     // 0x0030(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FString                                 DLSSEnable;                                        // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 DLSSQuality;                                       // 0x0048(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DLSSApply(int32 EntryPoint);
	void OnApply(class UPDA_SettingsData_C* SettingsData, const struct FFValueTypes& Value, class UBP_SettingsManager_C* SettingsManager);
	void OnPreApply(class UPDA_SettingsData_C* SettingsData, const struct FFValueTypes& Value, class UBP_SettingsManager_C* SettingsManager);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DLSSApply_C">();
	}
	static class UBP_DLSSApply_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DLSSApply_C>();
	}
};
static_assert(alignof(UBP_DLSSApply_C) == 0x000008, "Wrong alignment on UBP_DLSSApply_C");
static_assert(sizeof(UBP_DLSSApply_C) == 0x000058, "Wrong size on UBP_DLSSApply_C");
static_assert(offsetof(UBP_DLSSApply_C, UberGraphFrame_BP_DLSSApply_C) == 0x000030, "Member 'UBP_DLSSApply_C::UberGraphFrame_BP_DLSSApply_C' has a wrong offset!");
static_assert(offsetof(UBP_DLSSApply_C, DLSSEnable) == 0x000038, "Member 'UBP_DLSSApply_C::DLSSEnable' has a wrong offset!");
static_assert(offsetof(UBP_DLSSApply_C, DLSSQuality) == 0x000048, "Member 'UBP_DLSSApply_C::DLSSQuality' has a wrong offset!");

}

