#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FPCharacterBase

#include "Basic.hpp"

#include "BP_FPCharacterBase_classes.hpp"
#include "BP_FPCharacterBase_parameters.hpp"


namespace SDK
{

// Function BP_FPCharacterBase.BP_FPCharacterBase_C.BndEvt__FirstPersonStepManager_K2Node_ComponentBoundEvent_0_PlayFootstep__DelegateSignature
// (BlueprintEvent)
// Parameters:
// ECharacterMoveType                      MoveTypeOut                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ECharacterStairsType                    StairTypeOut                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ECharacterDeltaSpeed                    DeltaSpeedOut                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  MovementIntensity                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::BndEvt__FirstPersonStepManager_K2Node_ComponentBoundEvent_0_PlayFootstep__DelegateSignature(ECharacterMoveType MoveTypeOut, ECharacterStairsType StairTypeOut, ECharacterDeltaSpeed DeltaSpeedOut, double MovementIntensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "BndEvt__FirstPersonStepManager_K2Node_ComponentBoundEvent_0_PlayFootstep__DelegateSignature");

	Params::BP_FPCharacterBase_C_BndEvt__FirstPersonStepManager_K2Node_ComponentBoundEvent_0_PlayFootstep__DelegateSignature Parms{};

	Parms.MoveTypeOut = MoveTypeOut;
	Parms.StairTypeOut = StairTypeOut;
	Parms.DeltaSpeedOut = DeltaSpeedOut;
	Parms.MovementIntensity = MovementIntensity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.ExecuteUbergraph_BP_FPCharacterBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::ExecuteUbergraph_BP_FPCharacterBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "ExecuteUbergraph_BP_FPCharacterBase");

	Params::BP_FPCharacterBase_C_ExecuteUbergraph_BP_FPCharacterBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.FSModulator__FinishedFunc
// (BlueprintEvent)

void ABP_FPCharacterBase_C::FSModulator__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "FSModulator__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.FSModulator__UpdateFunc
// (BlueprintEvent)

void ABP_FPCharacterBase_C::FSModulator__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "FSModulator__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.InpActEvt_Sprint_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::InpActEvt_Sprint_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "InpActEvt_Sprint_K2Node_InputActionEvent_0");

	Params::BP_FPCharacterBase_C_InpActEvt_Sprint_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.InpActEvt_Sprint_K2Node_InputActionEvent_1
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::InpActEvt_Sprint_K2Node_InputActionEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "InpActEvt_Sprint_K2Node_InputActionEvent_1");

	Params::BP_FPCharacterBase_C_InpActEvt_Sprint_K2Node_InputActionEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.InpAxisEvt_ChangeTime_K2Node_InputAxisEvent_4
// (BlueprintEvent)
// Parameters:
// float                                   AxisValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::InpAxisEvt_ChangeTime_K2Node_InputAxisEvent_4(float AxisValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "InpAxisEvt_ChangeTime_K2Node_InputAxisEvent_4");

	Params::BP_FPCharacterBase_C_InpAxisEvt_ChangeTime_K2Node_InputAxisEvent_4 Parms{};

	Parms.AxisValue = AxisValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.InpAxisEvt_LookUp_K2Node_InputAxisEvent_1
// (BlueprintEvent)
// Parameters:
// float                                   AxisValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::InpAxisEvt_LookUp_K2Node_InputAxisEvent_1(float AxisValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "InpAxisEvt_LookUp_K2Node_InputAxisEvent_1");

	Params::BP_FPCharacterBase_C_InpAxisEvt_LookUp_K2Node_InputAxisEvent_1 Parms{};

	Parms.AxisValue = AxisValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.InpAxisEvt_MoveForward_K2Node_InputAxisEvent_2
// (BlueprintEvent)
// Parameters:
// float                                   AxisValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::InpAxisEvt_MoveForward_K2Node_InputAxisEvent_2(float AxisValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "InpAxisEvt_MoveForward_K2Node_InputAxisEvent_2");

	Params::BP_FPCharacterBase_C_InpAxisEvt_MoveForward_K2Node_InputAxisEvent_2 Parms{};

	Parms.AxisValue = AxisValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.InpAxisEvt_MoveRight_K2Node_InputAxisEvent_3
// (BlueprintEvent)
// Parameters:
// float                                   AxisValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::InpAxisEvt_MoveRight_K2Node_InputAxisEvent_3(float AxisValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "InpAxisEvt_MoveRight_K2Node_InputAxisEvent_3");

	Params::BP_FPCharacterBase_C_InpAxisEvt_MoveRight_K2Node_InputAxisEvent_3 Parms{};

	Parms.AxisValue = AxisValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.InpAxisEvt_Turn_K2Node_InputAxisEvent_0
// (BlueprintEvent)
// Parameters:
// float                                   AxisValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::InpAxisEvt_Turn_K2Node_InputAxisEvent_0(float AxisValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "InpAxisEvt_Turn_K2Node_InputAxisEvent_0");

	Params::BP_FPCharacterBase_C_InpAxisEvt_Turn_K2Node_InputAxisEvent_0 Parms{};

	Parms.AxisValue = AxisValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.IsThreat
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Threat                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::IsThreat(bool* Threat)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "IsThreat");

	Params::BP_FPCharacterBase_C_IsThreat Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Threat != nullptr)
		*Threat = Parms.Threat;
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.Play Music
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USoundCue*                        Music_Cue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::Play_Music(class USoundCue* Music_Cue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "Play Music");

	Params::BP_FPCharacterBase_C_Play_Music Parms{};

	Parms.Music_Cue = Music_Cue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FPCharacterBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FPCharacterBase_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "ReceiveTick");

	Params::BP_FPCharacterBase_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.ResetStep
// (BlueprintCallable, BlueprintEvent)

void ABP_FPCharacterBase_C::ResetStep()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "ResetStep");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.ShuffleModulator__FinishedFunc
// (BlueprintEvent)

void ABP_FPCharacterBase_C::ShuffleModulator__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "ShuffleModulator__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.ShuffleModulator__UpdateFunc
// (BlueprintEvent)

void ABP_FPCharacterBase_C::ShuffleModulator__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "ShuffleModulator__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FPCharacterBase.BP_FPCharacterBase_C.UpdateFootstepManager
// (BlueprintCallable, BlueprintEvent)

void ABP_FPCharacterBase_C::UpdateFootstepManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FPCharacterBase_C", "UpdateFootstepManager");

	UObject::ProcessEvent(Func, nullptr);
}

}

