#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: COIN_BIG_BP

#include "Basic.hpp"

#include "COIN_BIG_BP_classes.hpp"
#include "COIN_BIG_BP_parameters.hpp"


namespace SDK
{

// Function COIN_BIG_BP.COIN_BIG_BP_C.BndEvt__COIN_BP_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ACOIN_BIG_BP_C::BndEvt__COIN_BP_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("COIN_BIG_BP_C", "BndEvt__COIN_BP_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::COIN_BIG_BP_C_BndEvt__COIN_BP_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function COIN_BIG_BP.COIN_BIG_BP_C.CoinRotationStop
// (BlueprintCallable, BlueprintEvent)

void ACOIN_BIG_BP_C::CoinRotationStop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("COIN_BIG_BP_C", "CoinRotationStop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function COIN_BIG_BP.COIN_BIG_BP_C.ExecuteUbergraph_COIN_BIG_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACOIN_BIG_BP_C::ExecuteUbergraph_COIN_BIG_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("COIN_BIG_BP_C", "ExecuteUbergraph_COIN_BIG_BP");

	Params::COIN_BIG_BP_C_ExecuteUbergraph_COIN_BIG_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function COIN_BIG_BP.COIN_BIG_BP_C.Normal_Rotatio_TL__FinishedFunc
// (BlueprintEvent)

void ACOIN_BIG_BP_C::Normal_Rotatio_TL__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("COIN_BIG_BP_C", "Normal_Rotatio_TL__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function COIN_BIG_BP.COIN_BIG_BP_C.Normal_Rotatio_TL__UpdateFunc
// (BlueprintEvent)

void ACOIN_BIG_BP_C::Normal_Rotatio_TL__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("COIN_BIG_BP_C", "Normal_Rotatio_TL__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function COIN_BIG_BP.COIN_BIG_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ACOIN_BIG_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("COIN_BIG_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function COIN_BIG_BP.COIN_BIG_BP_C.Respawn_Coin
// (BlueprintCallable, BlueprintEvent)

void ACOIN_BIG_BP_C::Respawn_Coin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("COIN_BIG_BP_C", "Respawn_Coin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function COIN_BIG_BP.COIN_BIG_BP_C.TakeCoin_Rotation_TL__FinishedFunc
// (BlueprintEvent)

void ACOIN_BIG_BP_C::TakeCoin_Rotation_TL__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("COIN_BIG_BP_C", "TakeCoin_Rotation_TL__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function COIN_BIG_BP.COIN_BIG_BP_C.TakeCoin_Rotation_TL__UpdateFunc
// (BlueprintEvent)

void ACOIN_BIG_BP_C::TakeCoin_Rotation_TL__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("COIN_BIG_BP_C", "TakeCoin_Rotation_TL__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

