#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Fake_Button

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Fake_Button.Fake_Button_C.ExecuteUbergraph_Fake_Button
// 0x0010 (0x0010 - 0x0000)
struct Fake_Button_C_ExecuteUbergraph_Fake_Button final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsHovered;                           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bPlaySound;                           // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_414C[0x1];                                     // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Fake_Button_C_ExecuteUbergraph_Fake_Button) == 0x000008, "Wrong alignment on Fake_Button_C_ExecuteUbergraph_Fake_Button");
static_assert(sizeof(Fake_Button_C_ExecuteUbergraph_Fake_Button) == 0x000010, "Wrong size on Fake_Button_C_ExecuteUbergraph_Fake_Button");
static_assert(offsetof(Fake_Button_C_ExecuteUbergraph_Fake_Button, EntryPoint) == 0x000000, "Member 'Fake_Button_C_ExecuteUbergraph_Fake_Button::EntryPoint' has a wrong offset!");
static_assert(offsetof(Fake_Button_C_ExecuteUbergraph_Fake_Button, K2Node_Event_bIsHovered) == 0x000004, "Member 'Fake_Button_C_ExecuteUbergraph_Fake_Button::K2Node_Event_bIsHovered' has a wrong offset!");
static_assert(offsetof(Fake_Button_C_ExecuteUbergraph_Fake_Button, K2Node_Event_bPlaySound) == 0x000005, "Member 'Fake_Button_C_ExecuteUbergraph_Fake_Button::K2Node_Event_bPlaySound' has a wrong offset!");
static_assert(offsetof(Fake_Button_C_ExecuteUbergraph_Fake_Button, K2Node_Event_IsDesignTime) == 0x000006, "Member 'Fake_Button_C_ExecuteUbergraph_Fake_Button::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(Fake_Button_C_ExecuteUbergraph_Fake_Button, CallFunc_GetPlayerController_ReturnValue) == 0x000008, "Member 'Fake_Button_C_ExecuteUbergraph_Fake_Button::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");

// Function Fake_Button.Fake_Button_C.OnSetHoverEffect
// 0x0002 (0x0002 - 0x0000)
struct Fake_Button_C_OnSetHoverEffect final
{
public:
	bool                                          bIsHovered;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bPlaySound;                                        // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Fake_Button_C_OnSetHoverEffect) == 0x000001, "Wrong alignment on Fake_Button_C_OnSetHoverEffect");
static_assert(sizeof(Fake_Button_C_OnSetHoverEffect) == 0x000002, "Wrong size on Fake_Button_C_OnSetHoverEffect");
static_assert(offsetof(Fake_Button_C_OnSetHoverEffect, bIsHovered) == 0x000000, "Member 'Fake_Button_C_OnSetHoverEffect::bIsHovered' has a wrong offset!");
static_assert(offsetof(Fake_Button_C_OnSetHoverEffect, bPlaySound) == 0x000001, "Member 'Fake_Button_C_OnSetHoverEffect::bPlaySound' has a wrong offset!");

// Function Fake_Button.Fake_Button_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct Fake_Button_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Fake_Button_C_PreConstruct) == 0x000001, "Wrong alignment on Fake_Button_C_PreConstruct");
static_assert(sizeof(Fake_Button_C_PreConstruct) == 0x000001, "Wrong size on Fake_Button_C_PreConstruct");
static_assert(offsetof(Fake_Button_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'Fake_Button_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function Fake_Button.Fake_Button_C.SetGlobalSettings
// 0x0010 (0x0010 - 0x0000)
struct Fake_Button_C_SetGlobalSettings final
{
public:
	struct FLinearColor                           CustomColor;                                       // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Fake_Button_C_SetGlobalSettings) == 0x000004, "Wrong alignment on Fake_Button_C_SetGlobalSettings");
static_assert(sizeof(Fake_Button_C_SetGlobalSettings) == 0x000010, "Wrong size on Fake_Button_C_SetGlobalSettings");
static_assert(offsetof(Fake_Button_C_SetGlobalSettings, CustomColor) == 0x000000, "Member 'Fake_Button_C_SetGlobalSettings::CustomColor' has a wrong offset!");

// Function Fake_Button.Fake_Button_C.SetHoverEffect
// 0x0010 (0x0010 - 0x0000)
struct Fake_Button_C_SetHoverEffect final
{
public:
	bool                                          bIsHovered;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_414D[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Fake_Button_C_SetHoverEffect) == 0x000008, "Wrong alignment on Fake_Button_C_SetHoverEffect");
static_assert(sizeof(Fake_Button_C_SetHoverEffect) == 0x000010, "Wrong size on Fake_Button_C_SetHoverEffect");
static_assert(offsetof(Fake_Button_C_SetHoverEffect, bIsHovered) == 0x000000, "Member 'Fake_Button_C_SetHoverEffect::bIsHovered' has a wrong offset!");
static_assert(offsetof(Fake_Button_C_SetHoverEffect, CallFunc_GetPlayerController_ReturnValue) == 0x000008, "Member 'Fake_Button_C_SetHoverEffect::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");

}

