#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Fallow_Fish_bp_9

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass fallow_Fish_bp_9.fallow_Fish_bp_9_C
// 0x0048 (0x02E0 - 0x0298)
class AFallow_Fish_bp_9_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Audio;                                             // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Crocodile;                                         // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Sphere;                                            // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPFPathFollowerComponent*               PFPathFollower;                                    // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Delta_Rotation;                                    // 0x02C8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void BndEvt__Ballista_arrow_PFPathFollower_K2Node_ComponentBoundEvent_0_ReachedEndSignature__DelegateSignature(class UPFPathFollowerComponent* FollowerComp);
	void BndEvt__Ballista_arrow_PFPathFollower_K2Node_ComponentBoundEvent_1_ReachedStartSignature__DelegateSignature(class UPFPathFollowerComponent* FollowerComp);
	void BndEvt__fallow_Fish_bp_7_Box_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__fallow_Fish_bp_7_PFPathFollower_K2Node_ComponentBoundEvent_2_StartPathSignature__DelegateSignature(class UPFPathFollowerComponent* FollowerComp);
	void BndEvt__fallow_Fish_bp_9_crocodile_K2Node_ComponentBoundEvent_5_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void Char_Die_Restart();
	void ExecuteUbergraph_fallow_Fish_bp_9(int32 EntryPoint);
	void ReceiveBeginPlay();
	void Reset();
	void RestartSpawnEvent();
	void Shot();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"fallow_Fish_bp_9_C">();
	}
	static class AFallow_Fish_bp_9_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFallow_Fish_bp_9_C>();
	}
};
static_assert(alignof(AFallow_Fish_bp_9_C) == 0x000008, "Wrong alignment on AFallow_Fish_bp_9_C");
static_assert(sizeof(AFallow_Fish_bp_9_C) == 0x0002E0, "Wrong size on AFallow_Fish_bp_9_C");
static_assert(offsetof(AFallow_Fish_bp_9_C, UberGraphFrame) == 0x000298, "Member 'AFallow_Fish_bp_9_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AFallow_Fish_bp_9_C, Box) == 0x0002A0, "Member 'AFallow_Fish_bp_9_C::Box' has a wrong offset!");
static_assert(offsetof(AFallow_Fish_bp_9_C, Audio) == 0x0002A8, "Member 'AFallow_Fish_bp_9_C::Audio' has a wrong offset!");
static_assert(offsetof(AFallow_Fish_bp_9_C, Crocodile) == 0x0002B0, "Member 'AFallow_Fish_bp_9_C::Crocodile' has a wrong offset!");
static_assert(offsetof(AFallow_Fish_bp_9_C, Sphere) == 0x0002B8, "Member 'AFallow_Fish_bp_9_C::Sphere' has a wrong offset!");
static_assert(offsetof(AFallow_Fish_bp_9_C, PFPathFollower) == 0x0002C0, "Member 'AFallow_Fish_bp_9_C::PFPathFollower' has a wrong offset!");
static_assert(offsetof(AFallow_Fish_bp_9_C, Delta_Rotation) == 0x0002C8, "Member 'AFallow_Fish_bp_9_C::Delta_Rotation' has a wrong offset!");

}

