#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FarmerDaughter_AnimBlueprint

#include "Basic.hpp"

#include "FarmerDaughter_AnimBlueprint_classes.hpp"
#include "FarmerDaughter_AnimBlueprint_parameters.hpp"


namespace SDK
{

// Function FarmerDaughter_AnimBlueprint.FarmerDaughter_AnimBlueprint_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UFarmerDaughter_AnimBlueprint_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FarmerDaughter_AnimBlueprint_C", "AnimGraph");

	Params::FarmerDaughter_AnimBlueprint_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function FarmerDaughter_AnimBlueprint.FarmerDaughter_AnimBlueprint_C.ExecuteUbergraph_FarmerDaughter_AnimBlueprint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFarmerDaughter_AnimBlueprint_C::ExecuteUbergraph_FarmerDaughter_AnimBlueprint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FarmerDaughter_AnimBlueprint_C", "ExecuteUbergraph_FarmerDaughter_AnimBlueprint");

	Params::FarmerDaughter_AnimBlueprint_C_ExecuteUbergraph_FarmerDaughter_AnimBlueprint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

