#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Item_BOX_FlyDrop_BP

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Item_BOX_FlyDrop_BP.Item_BOX_FlyDrop_BP_C.UserConstructionScript
// 0x0008 (0x0008 - 0x0000)
struct Item_BOX_FlyDrop_BP_C_UserConstructionScript final
{
public:
	int32                                         CallFunc_RandomInteger_ReturnValue;                // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Item_BOX_FlyDrop_BP_C_UserConstructionScript) == 0x000004, "Wrong alignment on Item_BOX_FlyDrop_BP_C_UserConstructionScript");
static_assert(sizeof(Item_BOX_FlyDrop_BP_C_UserConstructionScript) == 0x000008, "Wrong size on Item_BOX_FlyDrop_BP_C_UserConstructionScript");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_UserConstructionScript, CallFunc_RandomInteger_ReturnValue) == 0x000000, "Member 'Item_BOX_FlyDrop_BP_C_UserConstructionScript::CallFunc_RandomInteger_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_UserConstructionScript, K2Node_SwitchInteger_CmpSuccess) == 0x000004, "Member 'Item_BOX_FlyDrop_BP_C_UserConstructionScript::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");

// Function Item_BOX_FlyDrop_BP.Item_BOX_FlyDrop_BP_C.ExecuteUbergraph_Item_BOX_FlyDrop_BP
// 0x01E0 (0x01E0 - 0x0000)
struct Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_30FD[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UALTF42_FullHUD_Widget_C*>       CallFunc_GetAllWidgetsOfClass_FoundWidgets;        // 0x0008(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_30FE[0x4];                                     // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue_1;          // 0x0040(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue_1;      // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue_2;          // 0x0060(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue;         // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x007D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x007E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_30FF[0x1];                                     // 0x007F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3100[0x3];                                     // 0x009D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x00A0(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_ActorHasTag_ReturnValue;                  // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3101[0x7];                                     // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AALTF4_Loco_BP_C*                       K2Node_DynamicCast_AsALTF4_Loco_BP;                // 0x0190(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3102[0x7];                                     // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x01A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UALTF42_GameInstance_C*                 K2Node_DynamicCast_AsALTF42_Game_Instance;         // 0x01A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x01B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x01B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x01B3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x01B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3103[0x4];                                     // 0x01BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UALTF42_FullHUD_Widget_C*               CallFunc_Array_Get_Item;                           // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3104[0x3];                                     // 0x01C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x01CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x01D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP) == 0x000008, "Wrong alignment on Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP");
static_assert(sizeof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP) == 0x0001E0, "Wrong size on Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, EntryPoint) == 0x000000, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_GetAllWidgetsOfClass_FoundWidgets) == 0x000008, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_GetAllWidgetsOfClass_FoundWidgets' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_GetSocketLocation_ReturnValue) == 0x000020, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_SpawnSystemAtLocation_ReturnValue) == 0x000038, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_SpawnSystemAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_GetSocketLocation_ReturnValue_1) == 0x000040, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_GetSocketLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_SpawnSystemAtLocation_ReturnValue_1) == 0x000058, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_SpawnSystemAtLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_GetSocketLocation_ReturnValue_2) == 0x000060, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_GetSocketLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_RandomIntegerInRange_ReturnValue) == 0x000078, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_RandomIntegerInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_SwitchInteger_CmpSuccess) == 0x00007C, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_SwitchEnum_CmpSuccess) == 0x00007D, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, Temp_bool_IsClosed_Variable) == 0x00007E, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000080, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_ComponentBoundEvent_OtherActor) == 0x000088, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_ComponentBoundEvent_OtherComp) == 0x000090, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000098, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_ComponentBoundEvent_bFromSweep) == 0x00009C, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_ComponentBoundEvent_SweepResult) == 0x0000A0, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_ActorHasTag_ReturnValue) == 0x000188, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_ActorHasTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_DynamicCast_AsALTF4_Loco_BP) == 0x000190, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_DynamicCast_AsALTF4_Loco_BP' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_DynamicCast_bSuccess) == 0x000198, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_GetGameInstance_ReturnValue) == 0x0001A0, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_DynamicCast_AsALTF42_Game_Instance) == 0x0001A8, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_DynamicCast_AsALTF42_Game_Instance' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, K2Node_DynamicCast_bSuccess_1) == 0x0001B0, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, Temp_bool_Has_Been_Initd_Variable) == 0x0001B1, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, Temp_bool_Has_Been_Initd_Variable_1) == 0x0001B2, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, Temp_bool_IsClosed_Variable_1) == 0x0001B3, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, Temp_int_Variable) == 0x0001B4, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_Add_IntInt_ReturnValue) == 0x0001B8, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_Array_Get_Item) == 0x0001C0, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_Less_IntInt_ReturnValue) == 0x0001C8, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_Add_IntInt_ReturnValue_1) == 0x0001CC, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_Add_IntInt_ReturnValue_2) == 0x0001D0, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_Add_IntInt_ReturnValue_3) == 0x0001D4, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_Add_IntInt_ReturnValue_4) == 0x0001D8, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP, CallFunc_Add_IntInt_ReturnValue_5) == 0x0001DC, "Member 'Item_BOX_FlyDrop_BP_C_ExecuteUbergraph_Item_BOX_FlyDrop_BP::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");

// Function Item_BOX_FlyDrop_BP.Item_BOX_FlyDrop_BP_C.BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3105[0x3];                                     // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'Item_BOX_FlyDrop_BP_C_BndEvt__Item_BOX_BP_Overlap_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

}

