#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MenuSettingsSaveGameBP

#include "Basic.hpp"

#include "MenuSettingsSaveGameBP_classes.hpp"
#include "MenuSettingsSaveGameBP_parameters.hpp"


namespace SDK
{

// Function MenuSettingsSaveGameBP.MenuSettingsSaveGameBP_C.GetPersistentVar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Param_Name                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, HasGetValueTypeHash)
// class FString                           Value                                                  (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    bFound                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMenuSettingsSaveGameBP_C::GetPersistentVar(const class FString& Param_Name, class FString* Value, bool* bFound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuSettingsSaveGameBP_C", "GetPersistentVar");

	Params::MenuSettingsSaveGameBP_C_GetPersistentVar Parms{};

	Parms.Param_Name = std::move(Param_Name);

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = std::move(Parms.Value);

	if (bFound != nullptr)
		*bFound = Parms.bFound;
}


// Function MenuSettingsSaveGameBP.MenuSettingsSaveGameBP_C.SetPersistentVar
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Param_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UMenuSettingsSaveGameBP_C::SetPersistentVar(const class FString& Param_Name, const class FString& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuSettingsSaveGameBP_C", "SetPersistentVar");

	Params::MenuSettingsSaveGameBP_C_SetPersistentVar Parms{};

	Parms.Param_Name = std::move(Param_Name);
	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}

}

