#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Skel_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "IKRig_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass NPC_Skel_AnimBP.NPC_Skel_AnimBP_C
// 0x0210 (0x0560 - 0x0350)
class UNPC_Skel_AnimBP_C final : public UAnimInstance
{
public:
	uint8                                         Pad_31CD[0x8];                                     // 0x0348(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0358(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0360(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0368(0x0020)()
	struct FAnimNode_RetargetPoseFromMesh         AnimGraphNode_RetargetPoseFromMesh;                // 0x0388(0x01D8)(ContainsInstancedReference)

public:
	void AnimGraph(struct FPoseLink* Param_AnimGraph);
	void ExecuteUbergraph_NPC_Skel_AnimBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPC_Skel_AnimBP_C">();
	}
	static class UNPC_Skel_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNPC_Skel_AnimBP_C>();
	}
};
static_assert(alignof(UNPC_Skel_AnimBP_C) == 0x000010, "Wrong alignment on UNPC_Skel_AnimBP_C");
static_assert(sizeof(UNPC_Skel_AnimBP_C) == 0x000560, "Wrong size on UNPC_Skel_AnimBP_C");
static_assert(offsetof(UNPC_Skel_AnimBP_C, UberGraphFrame) == 0x000350, "Member 'UNPC_Skel_AnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UNPC_Skel_AnimBP_C, AnimBlueprintExtension_PropertyAccess) == 0x000358, "Member 'UNPC_Skel_AnimBP_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UNPC_Skel_AnimBP_C, AnimBlueprintExtension_Base) == 0x000360, "Member 'UNPC_Skel_AnimBP_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UNPC_Skel_AnimBP_C, AnimGraphNode_Root) == 0x000368, "Member 'UNPC_Skel_AnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UNPC_Skel_AnimBP_C, AnimGraphNode_RetargetPoseFromMesh) == 0x000388, "Member 'UNPC_Skel_AnimBP_C::AnimGraphNode_RetargetPoseFromMesh' has a wrong offset!");

}

