#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Simple_Talk_Widget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Simple_Talk_Widget.Simple_Talk_Widget_C
// 0x0078 (0x0338 - 0x02C0)
class USimple_Talk_Widget_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Background;                                        // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             DialogueText;                                      // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon_Image;                                        // 0x02D8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ProfileImage;                                      // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                              SkipBox;                                           // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             SpeakerNameText;                                   // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             SpeakerNameText_1;                                 // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   NPC_NAme;                                          // 0x0300(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UObject*                                NPC_Image;                                         // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class FText                                   Talk_Text;                                         // 0x0320(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_Simple_Talk_Widget(int32 EntryPoint);
	class FText Get_DialogueText_Text_0();
	struct FSlateBrush Get_Icon_Image_Brush();
	struct FSlateBrush Get_NPCImage();
	class FText Get_NPCNameText();
	void Hide_Talk_Event();
	void Push_Visible(ESlateVisibility InVisibility);
	void TalkStart(const class FText& Param_NPC_NAme, class UObject* Param_NPC_Image, const class FText& Param_Talk_Text);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Simple_Talk_Widget_C">();
	}
	static class USimple_Talk_Widget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USimple_Talk_Widget_C>();
	}
};
static_assert(alignof(USimple_Talk_Widget_C) == 0x000008, "Wrong alignment on USimple_Talk_Widget_C");
static_assert(sizeof(USimple_Talk_Widget_C) == 0x000338, "Wrong size on USimple_Talk_Widget_C");
static_assert(offsetof(USimple_Talk_Widget_C, UberGraphFrame) == 0x0002C0, "Member 'USimple_Talk_Widget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, Background) == 0x0002C8, "Member 'USimple_Talk_Widget_C::Background' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, DialogueText) == 0x0002D0, "Member 'USimple_Talk_Widget_C::DialogueText' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, Icon_Image) == 0x0002D8, "Member 'USimple_Talk_Widget_C::Icon_Image' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, ProfileImage) == 0x0002E0, "Member 'USimple_Talk_Widget_C::ProfileImage' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, SkipBox) == 0x0002E8, "Member 'USimple_Talk_Widget_C::SkipBox' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, SpeakerNameText) == 0x0002F0, "Member 'USimple_Talk_Widget_C::SpeakerNameText' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, SpeakerNameText_1) == 0x0002F8, "Member 'USimple_Talk_Widget_C::SpeakerNameText_1' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, NPC_NAme) == 0x000300, "Member 'USimple_Talk_Widget_C::NPC_NAme' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, NPC_Image) == 0x000318, "Member 'USimple_Talk_Widget_C::NPC_Image' has a wrong offset!");
static_assert(offsetof(USimple_Talk_Widget_C, Talk_Text) == 0x000320, "Member 'USimple_Talk_Widget_C::Talk_Text' has a wrong offset!");

}

