#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tarzan_DialogueOvelap_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tarzan_DialogueOvelap_BP.Tarzan_DialogueOvelap_BP_C
// 0x0048 (0x02E0 - 0x0298)
class ATarzan_DialogueOvelap_BP_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Overlap;                                           // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USphereComponent*                       Sphere;                                            // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                NPC_Value;                                         // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class ACameraActor*                           TalkCam;                                           // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class ULevelSequence*                         MeetSequence;                                      // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AALTF4_Loco_BP_C*                       ALTF4_Char;                                        // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          TarzanEnd_Dialogue;                                // 0x02D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void ExecuteUbergraph_Tarzan_DialogueOvelap_BP(int32 EntryPoint);
	void ReceiveBeginPlay();
	void TalkReset();
	void TarzamSeq_Start_Event();
	void TarzanSeq_End_Event();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Tarzan_DialogueOvelap_BP_C">();
	}
	static class ATarzan_DialogueOvelap_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATarzan_DialogueOvelap_BP_C>();
	}
};
static_assert(alignof(ATarzan_DialogueOvelap_BP_C) == 0x000008, "Wrong alignment on ATarzan_DialogueOvelap_BP_C");
static_assert(sizeof(ATarzan_DialogueOvelap_BP_C) == 0x0002E0, "Wrong size on ATarzan_DialogueOvelap_BP_C");
static_assert(offsetof(ATarzan_DialogueOvelap_BP_C, UberGraphFrame) == 0x000298, "Member 'ATarzan_DialogueOvelap_BP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ATarzan_DialogueOvelap_BP_C, Overlap) == 0x0002A0, "Member 'ATarzan_DialogueOvelap_BP_C::Overlap' has a wrong offset!");
static_assert(offsetof(ATarzan_DialogueOvelap_BP_C, Sphere) == 0x0002A8, "Member 'ATarzan_DialogueOvelap_BP_C::Sphere' has a wrong offset!");
static_assert(offsetof(ATarzan_DialogueOvelap_BP_C, DefaultSceneRoot) == 0x0002B0, "Member 'ATarzan_DialogueOvelap_BP_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ATarzan_DialogueOvelap_BP_C, NPC_Value) == 0x0002B8, "Member 'ATarzan_DialogueOvelap_BP_C::NPC_Value' has a wrong offset!");
static_assert(offsetof(ATarzan_DialogueOvelap_BP_C, TalkCam) == 0x0002C0, "Member 'ATarzan_DialogueOvelap_BP_C::TalkCam' has a wrong offset!");
static_assert(offsetof(ATarzan_DialogueOvelap_BP_C, MeetSequence) == 0x0002C8, "Member 'ATarzan_DialogueOvelap_BP_C::MeetSequence' has a wrong offset!");
static_assert(offsetof(ATarzan_DialogueOvelap_BP_C, ALTF4_Char) == 0x0002D0, "Member 'ATarzan_DialogueOvelap_BP_C::ALTF4_Char' has a wrong offset!");
static_assert(offsetof(ATarzan_DialogueOvelap_BP_C, TarzanEnd_Dialogue) == 0x0002D8, "Member 'ATarzan_DialogueOvelap_BP_C::TarzanEnd_Dialogue' has a wrong offset!");

}

