#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tarzan_DialogueOvelap_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Tarzan_DialogueOvelap_BP.Tarzan_DialogueOvelap_BP_C.BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F0D[0x3];                                     // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'Tarzan_DialogueOvelap_BP_C_BndEvt__Tarzan_DialogueOvelap_BP_Overlap_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function Tarzan_DialogueOvelap_BP.Tarzan_DialogueOvelap_BP_C.ExecuteUbergraph_Tarzan_DialogueOvelap_BP
// 0x01F8 (0x01F8 - 0x0000)
struct Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F0E[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F0F[0x3];                                     // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F10[0x3];                                     // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    CallFunc_CreateLevelSequencePlayer_OutActor;       // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULevelSequencePlayer*                   CallFunc_CreateLevelSequencePlayer_ReturnValue;    // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class AMH_Tarzan_BP_C*>                CallFunc_GetAllActorsOfClass_OutActors;            // 0x0048(0x0010)(ReferenceParm)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AMH_Tarzan_BP_C*                        CallFunc_Array_Get_Item;                           // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F11[0x3];                                     // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class AMH_Tarzan_BP_C*>                CallFunc_GetAllActorsOfClass_OutActors_1;          // 0x0078(0x0010)(ReferenceParm)
	class AMH_Tarzan_BP_C*                        CallFunc_Array_Get_Item_1;                         // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0094(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F12[0x3];                                     // 0x0095(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue;         // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F13[0x3];                                     // 0x009D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABandPawn_BP_C*>                 CallFunc_GetAllActorsOfClass_OutActors_2;          // 0x00A0(0x0010)(ReferenceParm)
	class ABandPawn_BP_C*                         CallFunc_Array_Get_Item_2;                         // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F14[0x3];                                     // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_3;        // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue_1;         // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_4;        // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue_2;         // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F15[0x3];                                     // 0x00FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0100(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AALTF4_Loco_BP_C*                       K2Node_DynamicCast_AsALTF4_Loco_BP;                // 0x01E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP) == 0x000008, "Wrong alignment on Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP");
static_assert(sizeof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP) == 0x0001F8, "Wrong size on Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, EntryPoint) == 0x000000, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetPlayerController_ReturnValue) == 0x000008, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, Temp_int_Variable) == 0x000010, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, Temp_int_Variable_1) == 0x000014, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Add_IntInt_ReturnValue_1) == 0x00001C, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, Temp_int_Variable_2) == 0x000020, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, Temp_bool_Has_Been_Initd_Variable) == 0x000024, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Add_IntInt_ReturnValue_2) == 0x000028, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, Temp_bool_IsClosed_Variable) == 0x00002C, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetPlayerController_ReturnValue_1) == 0x000030, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_CreateLevelSequencePlayer_OutActor) == 0x000038, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_CreateLevelSequencePlayer_OutActor' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_CreateLevelSequencePlayer_ReturnValue) == 0x000040, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_CreateLevelSequencePlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetAllActorsOfClass_OutActors) == 0x000048, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetPlayerController_ReturnValue_2) == 0x000058, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetPlayerController_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Array_Get_Item) == 0x000060, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Array_Length_ReturnValue) == 0x000068, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Less_IntInt_ReturnValue) == 0x00006C, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetPlayerCharacter_ReturnValue) == 0x000070, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetPlayerCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetAllActorsOfClass_OutActors_1) == 0x000078, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetAllActorsOfClass_OutActors_1' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Array_Get_Item_1) == 0x000088, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Array_Length_ReturnValue_1) == 0x000090, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Less_IntInt_ReturnValue_1) == 0x000094, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_RandomIntegerInRange_ReturnValue) == 0x000098, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_RandomIntegerInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, K2Node_SwitchInteger_CmpSuccess) == 0x00009C, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetAllActorsOfClass_OutActors_2) == 0x0000A0, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetAllActorsOfClass_OutActors_2' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Array_Get_Item_2) == 0x0000B0, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Array_Length_ReturnValue_2) == 0x0000B8, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_Less_IntInt_ReturnValue_2) == 0x0000BC, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetPlayerController_ReturnValue_3) == 0x0000C0, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetPlayerController_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetPlayerCharacter_ReturnValue_1) == 0x0000C8, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetPlayerCharacter_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetPlayerController_ReturnValue_4) == 0x0000D0, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetPlayerController_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, CallFunc_GetPlayerCharacter_ReturnValue_2) == 0x0000D8, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::CallFunc_GetPlayerCharacter_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x0000E0, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, K2Node_ComponentBoundEvent_OtherActor) == 0x0000E8, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, K2Node_ComponentBoundEvent_OtherComp) == 0x0000F0, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x0000F8, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, K2Node_ComponentBoundEvent_bFromSweep) == 0x0000FC, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, K2Node_ComponentBoundEvent_SweepResult) == 0x000100, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, K2Node_DynamicCast_AsALTF4_Loco_BP) == 0x0001E8, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::K2Node_DynamicCast_AsALTF4_Loco_BP' has a wrong offset!");
static_assert(offsetof(Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP, K2Node_DynamicCast_bSuccess) == 0x0001F0, "Member 'Tarzan_DialogueOvelap_BP_C_ExecuteUbergraph_Tarzan_DialogueOvelap_BP::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

