#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TickOptToolkit

#include "Basic.hpp"

#include "TickOptToolkit_classes.hpp"
#include "TickOptToolkit_parameters.hpp"


namespace SDK
{

// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.RegisterDynamicSkinnedMeshComponent
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class USkinnedMeshComponent*            SkinnedMeshComponent                                   (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitAnimUpdateRateOptComponent::RegisterDynamicSkinnedMeshComponent(class USkinnedMeshComponent* SkinnedMeshComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "RegisterDynamicSkinnedMeshComponent");

	Params::TickOptToolkitAnimUpdateRateOptComponent_RegisterDynamicSkinnedMeshComponent Parms{};

	Parms.SkinnedMeshComponent = SkinnedMeshComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.SetAnimUpdateRateOptimizationsMode
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// ETickOptToolkitAnimUROMode              InAnimUpdateRateOptimizationsMode                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitAnimUpdateRateOptComponent::SetAnimUpdateRateOptimizationsMode(ETickOptToolkitAnimUROMode InAnimUpdateRateOptimizationsMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "SetAnimUpdateRateOptimizationsMode");

	Params::TickOptToolkitAnimUpdateRateOptComponent_SetAnimUpdateRateOptimizationsMode Parms{};

	Parms.InAnimUpdateRateOptimizationsMode = InAnimUpdateRateOptimizationsMode;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.SetDisableScreenSizeScale
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInDisableScreenSizeScale                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitAnimUpdateRateOptComponent::SetDisableScreenSizeScale(bool bInDisableScreenSizeScale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "SetDisableScreenSizeScale");

	Params::TickOptToolkitAnimUpdateRateOptComponent_SetDisableScreenSizeScale Parms{};

	Parms.bInDisableScreenSizeScale = bInDisableScreenSizeScale;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.SetForceEnableAnimUpdateRateOptimizations
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInForceEnableAnimUpdateRateOptimizations              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitAnimUpdateRateOptComponent::SetForceEnableAnimUpdateRateOptimizations(bool bInForceEnableAnimUpdateRateOptimizations)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "SetForceEnableAnimUpdateRateOptimizations");

	Params::TickOptToolkitAnimUpdateRateOptComponent_SetForceEnableAnimUpdateRateOptimizations Parms{};

	Parms.bInForceEnableAnimUpdateRateOptimizations = bInForceEnableAnimUpdateRateOptimizations;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.SetFramesSkippedScreenSizeThresholds
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TArray<float>                           InFramesSkippedScreenSizeThresholds                    (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UTickOptToolkitAnimUpdateRateOptComponent::SetFramesSkippedScreenSizeThresholds(const TArray<float>& InFramesSkippedScreenSizeThresholds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "SetFramesSkippedScreenSizeThresholds");

	Params::TickOptToolkitAnimUpdateRateOptComponent_SetFramesSkippedScreenSizeThresholds Parms{};

	Parms.InFramesSkippedScreenSizeThresholds = std::move(InFramesSkippedScreenSizeThresholds);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.SetLODToFramesSkipped
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TArray<int32>                           InLODToFramesSkipped                                   (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UTickOptToolkitAnimUpdateRateOptComponent::SetLODToFramesSkipped(const TArray<int32>& InLODToFramesSkipped)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "SetLODToFramesSkipped");

	Params::TickOptToolkitAnimUpdateRateOptComponent_SetLODToFramesSkipped Parms{};

	Parms.InLODToFramesSkipped = std::move(InLODToFramesSkipped);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.SetMaxFramesSkippedForInterpolation
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   InMaxFramesSkippedForInterpolation                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitAnimUpdateRateOptComponent::SetMaxFramesSkippedForInterpolation(int32 InMaxFramesSkippedForInterpolation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "SetMaxFramesSkippedForInterpolation");

	Params::TickOptToolkitAnimUpdateRateOptComponent_SetMaxFramesSkippedForInterpolation Parms{};

	Parms.InMaxFramesSkippedForInterpolation = InMaxFramesSkippedForInterpolation;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.SetNonRenderedFramesSkipped
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   InNonRenderedFramesSkipped                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitAnimUpdateRateOptComponent::SetNonRenderedFramesSkipped(int32 InNonRenderedFramesSkipped)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "SetNonRenderedFramesSkipped");

	Params::TickOptToolkitAnimUpdateRateOptComponent_SetNonRenderedFramesSkipped Parms{};

	Parms.InNonRenderedFramesSkipped = InNonRenderedFramesSkipped;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.GetAnimUpdateRateOptimizationsMode
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// ETickOptToolkitAnimUROMode              ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

ETickOptToolkitAnimUROMode UTickOptToolkitAnimUpdateRateOptComponent::GetAnimUpdateRateOptimizationsMode() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "GetAnimUpdateRateOptimizationsMode");

	Params::TickOptToolkitAnimUpdateRateOptComponent_GetAnimUpdateRateOptimizationsMode Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.GetFramesSkippedScreenSizeThresholds
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const TArray<float>                     ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const TArray<float> UTickOptToolkitAnimUpdateRateOptComponent::GetFramesSkippedScreenSizeThresholds() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "GetFramesSkippedScreenSizeThresholds");

	Params::TickOptToolkitAnimUpdateRateOptComponent_GetFramesSkippedScreenSizeThresholds Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.GetLODToFramesSkipped
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const TArray<int32>                     ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const TArray<int32> UTickOptToolkitAnimUpdateRateOptComponent::GetLODToFramesSkipped() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "GetLODToFramesSkipped");

	Params::TickOptToolkitAnimUpdateRateOptComponent_GetLODToFramesSkipped Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.GetMaxFramesSkippedForInterpolation
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UTickOptToolkitAnimUpdateRateOptComponent::GetMaxFramesSkippedForInterpolation() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "GetMaxFramesSkippedForInterpolation");

	Params::TickOptToolkitAnimUpdateRateOptComponent_GetMaxFramesSkippedForInterpolation Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.GetNonRenderedFramesSkipped
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UTickOptToolkitAnimUpdateRateOptComponent::GetNonRenderedFramesSkipped() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "GetNonRenderedFramesSkipped");

	Params::TickOptToolkitAnimUpdateRateOptComponent_GetNonRenderedFramesSkipped Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.ShouldDisableScreenSizeScale
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitAnimUpdateRateOptComponent::ShouldDisableScreenSizeScale() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "ShouldDisableScreenSizeScale");

	Params::TickOptToolkitAnimUpdateRateOptComponent_ShouldDisableScreenSizeScale Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitAnimUpdateRateOptComponent.ShouldForceEnableAnimUpdateRateOptimizations
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitAnimUpdateRateOptComponent::ShouldForceEnableAnimUpdateRateOptimizations() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitAnimUpdateRateOptComponent", "ShouldForceEnableAnimUpdateRateOptimizations");

	Params::TickOptToolkitAnimUpdateRateOptComponent_ShouldForceEnableAnimUpdateRateOptimizations Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitFocusComponent.SetFocusLayer
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// ETickOptToolkitFocusLayer               InFocusLayer                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitFocusComponent::SetFocusLayer(ETickOptToolkitFocusLayer InFocusLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitFocusComponent", "SetFocusLayer");

	Params::TickOptToolkitFocusComponent_SetFocusLayer Parms{};

	Parms.InFocusLayer = InFocusLayer;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitFocusComponent.ShouldTrack
// (Native, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitFocusComponent::ShouldTrack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitFocusComponent", "ShouldTrack");

	Params::TickOptToolkitFocusComponent_ShouldTrack Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitFocusComponent.GetFocusLayer
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// ETickOptToolkitFocusLayer               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

ETickOptToolkitFocusLayer UTickOptToolkitFocusComponent::GetFocusLayer() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitFocusComponent", "GetFocusLayer");

	Params::TickOptToolkitFocusComponent_GetFocusLayer Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.AddComponentTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UActorComponent*                  Component                                              (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::AddComponentTickControl(class UActorComponent* Component)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "AddComponentTickControl");

	Params::TickOptToolkitMimicComponent_AddComponentTickControl Parms{};

	Parms.Component = Component;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.AddTimelineTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UTimelineComponent*               Timeline                                               (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bSyncToWorld                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::AddTimelineTickControl(class UTimelineComponent* Timeline, bool bSyncToWorld)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "AddTimelineTickControl");

	Params::TickOptToolkitMimicComponent_AddTimelineTickControl Parms{};

	Parms.Timeline = Timeline;
	Parms.bSyncToWorld = bSyncToWorld;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.OnNewPawn
// (Final, Native, Protected)
// Parameters:
// class APawn*                            Pawn                                                   (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::OnNewPawn(class APawn* Pawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "OnNewPawn");

	Params::TickOptToolkitMimicComponent_OnNewPawn Parms{};

	Parms.Pawn = Pawn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.RegisterMimicTarget
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UTickOptToolkitTargetComponent*   Target                                                 (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::RegisterMimicTarget(class UTickOptToolkitTargetComponent* Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "RegisterMimicTarget");

	Params::TickOptToolkitMimicComponent_RegisterMimicTarget Parms{};

	Parms.Target = Target;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.RemoveComponentTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UActorComponent*                  Component                                              (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::RemoveComponentTickControl(class UActorComponent* Component)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "RemoveComponentTickControl");

	Params::TickOptToolkitMimicComponent_RemoveComponentTickControl Parms{};

	Parms.Component = Component;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.RemoveTimelineTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UTimelineComponent*               Timeline                                               (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::RemoveTimelineTickControl(class UTimelineComponent* Timeline)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "RemoveTimelineTickControl");

	Params::TickOptToolkitMimicComponent_RemoveTimelineTickControl Parms{};

	Parms.Timeline = Timeline;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.SetActorTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInActorTickControl                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::SetActorTickControl(bool bInActorTickControl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "SetActorTickControl");

	Params::TickOptToolkitMimicComponent_SetActorTickControl Parms{};

	Parms.bInActorTickControl = bInActorTickControl;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.SetComponentsTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInComponentsTickControl                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::SetComponentsTickControl(bool bInComponentsTickControl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "SetComponentsTickControl");

	Params::TickOptToolkitMimicComponent_SetComponentsTickControl Parms{};

	Parms.bInComponentsTickControl = bInComponentsTickControl;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.SetSyncTimelinesToWorld
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInSyncTimelinesToWorld                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::SetSyncTimelinesToWorld(bool bInSyncTimelinesToWorld)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "SetSyncTimelinesToWorld");

	Params::TickOptToolkitMimicComponent_SetSyncTimelinesToWorld Parms{};

	Parms.bInSyncTimelinesToWorld = bInSyncTimelinesToWorld;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.SetTimelinesTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInTimelinesTickControl                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitMimicComponent::SetTimelinesTickControl(bool bInTimelinesTickControl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "SetTimelinesTickControl");

	Params::TickOptToolkitMimicComponent_SetTimelinesTickControl Parms{};

	Parms.bInTimelinesTickControl = bInTimelinesTickControl;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.UnregisterMimicTarget
// (Final, Native, Public, BlueprintCallable)

void UTickOptToolkitMimicComponent::UnregisterMimicTarget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "UnregisterMimicTarget");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.IsActorTickControl
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitMimicComponent::IsActorTickControl() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "IsActorTickControl");

	Params::TickOptToolkitMimicComponent_IsActorTickControl Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.IsComponentsTickControl
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitMimicComponent::IsComponentsTickControl() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "IsComponentsTickControl");

	Params::TickOptToolkitMimicComponent_IsComponentsTickControl Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.IsSyncTimelinesToWorld
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitMimicComponent::IsSyncTimelinesToWorld() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "IsSyncTimelinesToWorld");

	Params::TickOptToolkitMimicComponent_IsSyncTimelinesToWorld Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitMimicComponent.IsTimelinesTickControl
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitMimicComponent::IsTimelinesTickControl() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitMimicComponent", "IsTimelinesTickControl");

	Params::TickOptToolkitMimicComponent_IsTimelinesTickControl Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.AddComponentTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UActorComponent*                  Component                                              (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::AddComponentTickControl(class UActorComponent* Component)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "AddComponentTickControl");

	Params::TickOptToolkitTargetComponent_AddComponentTickControl Parms{};

	Parms.Component = Component;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.AddTimelineTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UTimelineComponent*               Timeline                                               (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bSyncToWorld                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::AddTimelineTickControl(class UTimelineComponent* Timeline, bool bSyncToWorld)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "AddTimelineTickControl");

	Params::TickOptToolkitTargetComponent_AddTimelineTickControl Parms{};

	Parms.Timeline = Timeline;
	Parms.bSyncToWorld = bSyncToWorld;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.Force
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   InZone                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInVisible                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::Force(int32 InZone, bool bInVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "Force");

	Params::TickOptToolkitTargetComponent_Force Parms{};

	Parms.InZone = InZone;
	Parms.bInVisible = bInVisible;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.Release
// (Final, Native, Public, BlueprintCallable)

void UTickOptToolkitTargetComponent::Release()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "Release");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.RemoveComponentTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UActorComponent*                  Component                                              (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::RemoveComponentTickControl(class UActorComponent* Component)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "RemoveComponentTickControl");

	Params::TickOptToolkitTargetComponent_RemoveComponentTickControl Parms{};

	Parms.Component = Component;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.RemoveTimelineTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UTimelineComponent*               Timeline                                               (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::RemoveTimelineTickControl(class UTimelineComponent* Timeline)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "RemoveTimelineTickControl");

	Params::TickOptToolkitTargetComponent_RemoveTimelineTickControl Parms{};

	Parms.Timeline = Timeline;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetActorTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInActorTickControl                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetActorTickControl(bool bInActorTickControl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetActorTickControl");

	Params::TickOptToolkitTargetComponent_SetActorTickControl Parms{};

	Parms.bInActorTickControl = bInActorTickControl;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetBoxExtents
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct FVector                          InExtents                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetBoxExtents(const struct FVector& InExtents)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetBoxExtents");

	Params::TickOptToolkitTargetComponent_SetBoxExtents Parms{};

	Parms.InExtents = std::move(InExtents);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetBoxRotation
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InRotation                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetBoxRotation(float InRotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetBoxRotation");

	Params::TickOptToolkitTargetComponent_SetBoxRotation Parms{};

	Parms.InRotation = InRotation;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetBufferSize
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InBufferSize                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetBufferSize(float InBufferSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetBufferSize");

	Params::TickOptToolkitTargetComponent_SetBufferSize Parms{};

	Parms.InBufferSize = InBufferSize;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetComponentsTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInComponentsTickControl                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetComponentsTickControl(bool bInComponentsTickControl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetComponentsTickControl");

	Params::TickOptToolkitTargetComponent_SetComponentsTickControl Parms{};

	Parms.bInComponentsTickControl = bInComponentsTickControl;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetDisableDistanceScale
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInDisableDistanceScale                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetDisableDistanceScale(bool bInDisableDistanceScale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetDisableDistanceScale");

	Params::TickOptToolkitTargetComponent_SetDisableDistanceScale Parms{};

	Parms.bInDisableDistanceScale = bInDisableDistanceScale;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetDistanceMode
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// ETickOptToolkitDistanceMode             InDistanceMode                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetDistanceMode(ETickOptToolkitDistanceMode InDistanceMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetDistanceMode");

	Params::TickOptToolkitTargetComponent_SetDistanceMode Parms{};

	Parms.InDistanceMode = InDistanceMode;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetFocusLayerMask
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   InFocusLayerMask                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetFocusLayerMask(int32 InFocusLayerMask)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetFocusLayerMask");

	Params::TickOptToolkitTargetComponent_SetFocusLayerMask Parms{};

	Parms.InFocusLayerMask = InFocusLayerMask;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetForceExecuteFirstTick
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInForceExecuteFirstTick                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetForceExecuteFirstTick(bool bInForceExecuteFirstTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetForceExecuteFirstTick");

	Params::TickOptToolkitTargetComponent_SetForceExecuteFirstTick Parms{};

	Parms.bInForceExecuteFirstTick = bInForceExecuteFirstTick;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetMidZoneSizes
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TArray<float>                           InMidZoneSizes                                         (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetMidZoneSizes(const TArray<float>& InMidZoneSizes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetMidZoneSizes");

	Params::TickOptToolkitTargetComponent_SetMidZoneSizes Parms{};

	Parms.InMidZoneSizes = std::move(InMidZoneSizes);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetSphereRadius
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InRadius                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetSphereRadius(float InRadius)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetSphereRadius");

	Params::TickOptToolkitTargetComponent_SetSphereRadius Parms{};

	Parms.InRadius = InRadius;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetSyncTimelinesToWorld
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInSyncTimelinesToWorld                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetSyncTimelinesToWorld(bool bInSyncTimelinesToWorld)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetSyncTimelinesToWorld");

	Params::TickOptToolkitTargetComponent_SetSyncTimelinesToWorld Parms{};

	Parms.bInSyncTimelinesToWorld = bInSyncTimelinesToWorld;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetTickSettings
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TArray<struct FTickOptToolkitTickSettings>InTickSettings                                         (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetTickSettings(const TArray<struct FTickOptToolkitTickSettings>& InTickSettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetTickSettings");

	Params::TickOptToolkitTargetComponent_SetTickSettings Parms{};

	Parms.InTickSettings = std::move(InTickSettings);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetTimelinesTickControl
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bInTimelinesTickControl                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetTimelinesTickControl(bool bInTimelinesTickControl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetTimelinesTickControl");

	Params::TickOptToolkitTargetComponent_SetTimelinesTickControl Parms{};

	Parms.bInTimelinesTickControl = bInTimelinesTickControl;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.SetVisibilityMode
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// ETickByVisibilityMode                   InVisibilityMode                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTickOptToolkitTargetComponent::SetVisibilityMode(ETickByVisibilityMode InVisibilityMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "SetVisibilityMode");

	Params::TickOptToolkitTargetComponent_SetVisibilityMode Parms{};

	Parms.InVisibilityMode = InVisibilityMode;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetBoxExtents
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector UTickOptToolkitTargetComponent::GetBoxExtents() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetBoxExtents");

	Params::TickOptToolkitTargetComponent_GetBoxExtents Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetBoxRotation
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UTickOptToolkitTargetComponent::GetBoxRotation() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetBoxRotation");

	Params::TickOptToolkitTargetComponent_GetBoxRotation Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetBufferSize
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UTickOptToolkitTargetComponent::GetBufferSize() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetBufferSize");

	Params::TickOptToolkitTargetComponent_GetBufferSize Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetDistanceMode
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// ETickOptToolkitDistanceMode             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

ETickOptToolkitDistanceMode UTickOptToolkitTargetComponent::GetDistanceMode() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetDistanceMode");

	Params::TickOptToolkitTargetComponent_GetDistanceMode Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetFocusLayerMask
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UTickOptToolkitTargetComponent::GetFocusLayerMask() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetFocusLayerMask");

	Params::TickOptToolkitTargetComponent_GetFocusLayerMask Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetMidZoneSizes
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const TArray<float>                     ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const TArray<float> UTickOptToolkitTargetComponent::GetMidZoneSizes() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetMidZoneSizes");

	Params::TickOptToolkitTargetComponent_GetMidZoneSizes Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetSphereRadius
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UTickOptToolkitTargetComponent::GetSphereRadius() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetSphereRadius");

	Params::TickOptToolkitTargetComponent_GetSphereRadius Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetTickSettings
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const TArray<struct FTickOptToolkitTickSettings>ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const TArray<struct FTickOptToolkitTickSettings> UTickOptToolkitTargetComponent::GetTickSettings() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetTickSettings");

	Params::TickOptToolkitTargetComponent_GetTickSettings Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetTickZone
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UTickOptToolkitTargetComponent::GetTickZone() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetTickZone");

	Params::TickOptToolkitTargetComponent_GetTickZone Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.GetVisibilityMode
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// ETickByVisibilityMode                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

ETickByVisibilityMode UTickOptToolkitTargetComponent::GetVisibilityMode() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "GetVisibilityMode");

	Params::TickOptToolkitTargetComponent_GetVisibilityMode Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.IsActorTickControl
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitTargetComponent::IsActorTickControl() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "IsActorTickControl");

	Params::TickOptToolkitTargetComponent_IsActorTickControl Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.IsComponentsTickControl
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitTargetComponent::IsComponentsTickControl() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "IsComponentsTickControl");

	Params::TickOptToolkitTargetComponent_IsComponentsTickControl Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.IsForced
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitTargetComponent::IsForced() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "IsForced");

	Params::TickOptToolkitTargetComponent_IsForced Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.IsSyncTimelinesToWorld
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitTargetComponent::IsSyncTimelinesToWorld() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "IsSyncTimelinesToWorld");

	Params::TickOptToolkitTargetComponent_IsSyncTimelinesToWorld Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.IsTickVisible
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitTargetComponent::IsTickVisible() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "IsTickVisible");

	Params::TickOptToolkitTargetComponent_IsTickVisible Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.IsTimelinesTickControl
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitTargetComponent::IsTimelinesTickControl() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "IsTimelinesTickControl");

	Params::TickOptToolkitTargetComponent_IsTimelinesTickControl Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.ShouldDisableDistanceScale
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitTargetComponent::ShouldDisableDistanceScale() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "ShouldDisableDistanceScale");

	Params::TickOptToolkitTargetComponent_ShouldDisableDistanceScale Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TickOptToolkit.TickOptToolkitTargetComponent.ShouldForceExecuteFirstTick
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UTickOptToolkitTargetComponent::ShouldForceExecuteFirstTick() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TickOptToolkitTargetComponent", "ShouldForceExecuteFirstTick");

	Params::TickOptToolkitTargetComponent_ShouldForceExecuteFirstTick Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

