#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tutorial_Enemy_Respawn_BP

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Tutorial_Enemy_Respawn_BP.Tutorial_Enemy_Respawn_BP_C.Enemy_Die_SettingEvent
// 0x0001 (0x0001 - 0x0000)
struct Tutorial_Enemy_Respawn_BP_C_Enemy_Die_SettingEvent final
{
public:
	bool                                          Param_Char_Die;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Tutorial_Enemy_Respawn_BP_C_Enemy_Die_SettingEvent) == 0x000001, "Wrong alignment on Tutorial_Enemy_Respawn_BP_C_Enemy_Die_SettingEvent");
static_assert(sizeof(Tutorial_Enemy_Respawn_BP_C_Enemy_Die_SettingEvent) == 0x000001, "Wrong size on Tutorial_Enemy_Respawn_BP_C_Enemy_Die_SettingEvent");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_Enemy_Die_SettingEvent, Param_Char_Die) == 0x000000, "Member 'Tutorial_Enemy_Respawn_BP_C_Enemy_Die_SettingEvent::Param_Char_Die' has a wrong offset!");

// Function Tutorial_Enemy_Respawn_BP.Tutorial_Enemy_Respawn_BP_C.ExecuteUbergraph_Tutorial_Enemy_Respawn_BP
// 0x0130 (0x0130 - 0x0000)
struct Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Char_Die;                       // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34F8[0xB];                                     // 0x0005(0x000B)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x0010(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0070(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0088(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x00A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34F9[0x8];                                     // 0x00B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x00C0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x0128(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP) == 0x000010, "Wrong alignment on Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP");
static_assert(sizeof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP) == 0x000130, "Wrong size on Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP, EntryPoint) == 0x000000, "Member 'Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP, K2Node_CustomEvent_Char_Die) == 0x000004, "Member 'Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP::K2Node_CustomEvent_Char_Die' has a wrong offset!");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x000010, "Member 'Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP, CallFunc_BreakTransform_Location) == 0x000070, "Member 'Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP, CallFunc_BreakTransform_Rotation) == 0x000088, "Member 'Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP, CallFunc_BreakTransform_Scale) == 0x0000A0, "Member 'Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP, CallFunc_MakeTransform_ReturnValue) == 0x0000C0, "Member 'Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000120, "Member 'Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP, CallFunc_FinishSpawningActor_ReturnValue) == 0x000128, "Member 'Tutorial_Enemy_Respawn_BP_C_ExecuteUbergraph_Tutorial_Enemy_Respawn_BP::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");

}

