#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Vector2DN

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Vector2DN.Vector2DN
// 0x0008 (0x0008 - 0x0000)
struct FVector2DN final
{
public:
	float                                         X_2_61690A0C49AE65EEBEA3F1869ED7C8B0;              // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Y_4_99EA40724D71AB71DA2E298FBE765633;              // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FVector2DN) == 0x000004, "Wrong alignment on FVector2DN");
static_assert(sizeof(FVector2DN) == 0x000008, "Wrong size on FVector2DN");
static_assert(offsetof(FVector2DN, X_2_61690A0C49AE65EEBEA3F1869ED7C8B0) == 0x000000, "Member 'FVector2DN::X_2_61690A0C49AE65EEBEA3F1869ED7C8B0' has a wrong offset!");
static_assert(offsetof(FVector2DN, Y_4_99EA40724D71AB71DA2E298FBE765633) == 0x000004, "Member 'FVector2DN::Y_4_99EA40724D71AB71DA2E298FBE765633' has a wrong offset!");

}

