#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ButtonBase

#include "Basic.hpp"

#include "WBP_ButtonBase_classes.hpp"
#include "WBP_ButtonBase_parameters.hpp"


namespace SDK
{

// Function WBP_ButtonBase.WBP_ButtonBase_C.ApplyWidgetStyleActive
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ButtonBase_C::ApplyWidgetStyleActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "ApplyWidgetStyleActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.ApplyWidgetStyleDisabled
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ButtonBase_C::ApplyWidgetStyleDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "ApplyWidgetStyleDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.ApplyWidgetStyleHighlighted
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ButtonBase_C::ApplyWidgetStyleHighlighted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "ApplyWidgetStyleHighlighted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.ApplyWidgetStyleNormal
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ButtonBase_C::ApplyWidgetStyleNormal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "ApplyWidgetStyleNormal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ButtonBase_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.ExecuteUbergraph_WBP_ButtonBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ButtonBase_C::ExecuteUbergraph_WBP_ButtonBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "ExecuteUbergraph_WBP_ButtonBase");

	Params::WBP_ButtonBase_C_ExecuteUbergraph_WBP_ButtonBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OnButtonClicked
// (BlueprintCallable, BlueprintEvent)

void UWBP_ButtonBase_C::OnButtonClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OnButtonClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OnButtonHovered
// (BlueprintCallable, BlueprintEvent)

void UWBP_ButtonBase_C::OnButtonHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OnButtonHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.SetupButtonText
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ButtonBase_C::SetupButtonText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "SetupButtonText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OnPressedBack
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FKeyEvent                        KeyEvent                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ButtonBase_C::OnPressedBack(const struct FKeyEvent& KeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OnPressedBack");

	Params::WBP_ButtonBase_C_OnPressedBack Parms{};

	Parms.KeyEvent = std::move(KeyEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OnPressedDown
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FKeyEvent                        KeyEvent                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ButtonBase_C::OnPressedDown(const struct FKeyEvent& KeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OnPressedDown");

	Params::WBP_ButtonBase_C_OnPressedDown Parms{};

	Parms.KeyEvent = std::move(KeyEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OnPressedLeft
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FKeyEvent                        KeyEvent                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ButtonBase_C::OnPressedLeft(const struct FKeyEvent& KeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OnPressedLeft");

	Params::WBP_ButtonBase_C_OnPressedLeft Parms{};

	Parms.KeyEvent = std::move(KeyEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OnPressedRight
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FKeyEvent                        KeyEvent                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ButtonBase_C::OnPressedRight(const struct FKeyEvent& KeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OnPressedRight");

	Params::WBP_ButtonBase_C_OnPressedRight Parms{};

	Parms.KeyEvent = std::move(KeyEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OnPressedSelect
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FKeyEvent                        KeyEvent                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ButtonBase_C::OnPressedSelect(const struct FKeyEvent& KeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OnPressedSelect");

	Params::WBP_ButtonBase_C_OnPressedSelect Parms{};

	Parms.KeyEvent = std::move(KeyEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OnPressedUp
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FKeyEvent                        KeyEvent                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ButtonBase_C::OnPressedUp(const struct FKeyEvent& KeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OnPressedUp");

	Params::WBP_ButtonBase_C_OnPressedUp Parms{};

	Parms.KeyEvent = std::move(KeyEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OnSetHighlightEffect
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EWidgetStyleState                       Param_HighlightState                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bPlaySound                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ButtonBase_C::OnSetHighlightEffect(EWidgetStyleState Param_HighlightState, bool bPlaySound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OnSetHighlightEffect");

	Params::WBP_ButtonBase_C_OnSetHighlightEffect Parms{};

	Parms.Param_HighlightState = Param_HighlightState;
	Parms.bPlaySound = bPlaySound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.OverrideWidgetStyleFromConfig
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_ButtonBase_C::OverrideWidgetStyleFromConfig()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "OverrideWidgetStyleFromConfig");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ButtonBase_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "PreConstruct");

	Params::WBP_ButtonBase_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ButtonBase.WBP_ButtonBase_C.SetWidgetState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EWidgetStyleState                       Param_WidgetState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ButtonBase_C::SetWidgetState(EWidgetStyleState Param_WidgetState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ButtonBase_C", "SetWidgetState");

	Params::WBP_ButtonBase_C_SetWidgetState Parms{};

	Parms.Param_WidgetState = Param_WidgetState;

	UObject::ProcessEvent(Func, &Parms);
}

}

