#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BlackIn_Out_Widget

#include "Basic.hpp"


namespace SDK::Params
{

// Function BlackIn_Out_Widget.BlackIn_Out_Widget_C.ExecuteUbergraph_BlackIn_Out_Widget
// 0x0010 (0x0010 - 0x0000)
struct BlackIn_Out_Widget_C_ExecuteUbergraph_BlackIn_Out_Widget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E96[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BlackIn_Out_Widget_C_ExecuteUbergraph_BlackIn_Out_Widget) == 0x000008, "Wrong alignment on BlackIn_Out_Widget_C_ExecuteUbergraph_BlackIn_Out_Widget");
static_assert(sizeof(BlackIn_Out_Widget_C_ExecuteUbergraph_BlackIn_Out_Widget) == 0x000010, "Wrong size on BlackIn_Out_Widget_C_ExecuteUbergraph_BlackIn_Out_Widget");
static_assert(offsetof(BlackIn_Out_Widget_C_ExecuteUbergraph_BlackIn_Out_Widget, EntryPoint) == 0x000000, "Member 'BlackIn_Out_Widget_C_ExecuteUbergraph_BlackIn_Out_Widget::EntryPoint' has a wrong offset!");
static_assert(offsetof(BlackIn_Out_Widget_C_ExecuteUbergraph_BlackIn_Out_Widget, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'BlackIn_Out_Widget_C_ExecuteUbergraph_BlackIn_Out_Widget::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

}

