#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Horse_Enemy

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_Horse_Enemy.BP_Horse_Enemy_C.BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3554[0x3];                                     // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_OverlapCheck_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function BP_Horse_Enemy.BP_Horse_Enemy_C.BndEvt__BP_Horse_Enemy_PFPathFollower_K2Node_ComponentBoundEvent_0_ReachedEndSignature__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_PFPathFollower_K2Node_ComponentBoundEvent_0_ReachedEndSignature__DelegateSignature final
{
public:
	class UPFPathFollowerComponent*               FollowerComp;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_PFPathFollower_K2Node_ComponentBoundEvent_0_ReachedEndSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_PFPathFollower_K2Node_ComponentBoundEvent_0_ReachedEndSignature__DelegateSignature");
static_assert(sizeof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_PFPathFollower_K2Node_ComponentBoundEvent_0_ReachedEndSignature__DelegateSignature) == 0x000008, "Wrong size on BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_PFPathFollower_K2Node_ComponentBoundEvent_0_ReachedEndSignature__DelegateSignature");
static_assert(offsetof(BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_PFPathFollower_K2Node_ComponentBoundEvent_0_ReachedEndSignature__DelegateSignature, FollowerComp) == 0x000000, "Member 'BP_Horse_Enemy_C_BndEvt__BP_Horse_Enemy_PFPathFollower_K2Node_ComponentBoundEvent_0_ReachedEndSignature__DelegateSignature::FollowerComp' has a wrong offset!");

// Function BP_Horse_Enemy.BP_Horse_Enemy_C.ExecuteUbergraph_BP_Horse_Enemy
// 0x01E8 (0x01E8 - 0x0000)
struct BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3555[0x1];                                     // 0x0017(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3556[0x4];                                     // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AALTF4_Loco_BP_C*                       K2Node_DynamicCast_AsALTF4_Loco_BP;                // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3557[0x3];                                     // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_2;                               // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ABP_Horse_Enemy_C*>              CallFunc_GetAllActorsOfClass_OutActors;            // 0x0038(0x0010)(ReferenceParm)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3558[0x4];                                     // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Horse_Enemy_C*                      CallFunc_Array_Get_Item;                           // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3559[0x3];                                     // 0x005D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_Horse_Enemy_C*>              CallFunc_GetAllActorsOfClass_OutActors_1;          // 0x0060(0x0010)(ReferenceParm)
	class ABP_Horse_Enemy_C*                      CallFunc_Array_Get_Item_1;                         // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x007D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_355A[0x2];                                     // 0x007E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_Horse_Enemy_C*>              CallFunc_GetAllActorsOfClass_OutActors_2;          // 0x0080(0x0010)(ReferenceParm)
	class ABP_Horse_Enemy_C*                      CallFunc_Array_Get_Item_2;                         // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_355B[0x3];                                     // 0x009D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue_1;         // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AALTF4_Loco_BP_C*                       K2Node_DynamicCast_AsALTF4_Loco_BP_1;              // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_355C[0x3];                                     // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetDistanceTo_ReturnValue;                // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPFPathFollowerComponent*               K2Node_ComponentBoundEvent_followerComp;           // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_355D[0x3];                                     // 0x00DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x00E0(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AALTF4_Loco_BP_C*                       K2Node_DynamicCast_AsALTF4_Loco_BP_2;              // 0x01C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x01D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue_1;          // 0x01D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_355E[0x5];                                     // 0x01D3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast_1;       // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy) == 0x000008, "Wrong alignment on BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy");
static_assert(sizeof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy) == 0x0001E8, "Wrong size on BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, EntryPoint) == 0x000000, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, Temp_int_Variable) == 0x000004, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, Temp_int_Variable_1) == 0x000008, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Add_IntInt_ReturnValue_1) == 0x000010, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, Temp_bool_Has_Been_Initd_Variable) == 0x000014, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, Temp_bool_IsClosed_Variable) == 0x000015, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, Temp_bool_Has_Been_Initd_Variable_1) == 0x000016, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_GetPlayerCharacter_ReturnValue) == 0x000018, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_GetPlayerCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_Event_DeltaSeconds) == 0x000020, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_DynamicCast_AsALTF4_Loco_BP) == 0x000028, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_DynamicCast_AsALTF4_Loco_BP' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, Temp_int_Variable_2) == 0x000034, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_GetAllActorsOfClass_OutActors) == 0x000038, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Add_IntInt_ReturnValue_2) == 0x000048, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Array_Get_Item) == 0x000050, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Array_Length_ReturnValue) == 0x000058, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Less_IntInt_ReturnValue) == 0x00005C, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_GetAllActorsOfClass_OutActors_1) == 0x000060, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_GetAllActorsOfClass_OutActors_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Array_Get_Item_1) == 0x000070, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Array_Length_ReturnValue_1) == 0x000078, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Less_IntInt_ReturnValue_1) == 0x00007C, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, Temp_bool_IsClosed_Variable_1) == 0x00007D, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_GetAllActorsOfClass_OutActors_2) == 0x000080, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_GetAllActorsOfClass_OutActors_2' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Array_Get_Item_2) == 0x000090, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Array_Length_ReturnValue_2) == 0x000098, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Less_IntInt_ReturnValue_2) == 0x00009C, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_GetPlayerCharacter_ReturnValue_1) == 0x0000A0, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_GetPlayerCharacter_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_DynamicCast_AsALTF4_Loco_BP_1) == 0x0000A8, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_DynamicCast_AsALTF4_Loco_BP_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_DynamicCast_bSuccess_1) == 0x0000B0, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_GetDistanceTo_ReturnValue) == 0x0000B4, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_GetDistanceTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_ComponentBoundEvent_followerComp) == 0x0000B8, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_ComponentBoundEvent_followerComp' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x0000C0, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_ComponentBoundEvent_OtherActor) == 0x0000C8, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_ComponentBoundEvent_OtherComp) == 0x0000D0, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x0000D8, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_ComponentBoundEvent_bFromSweep) == 0x0000DC, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_ComponentBoundEvent_SweepResult) == 0x0000E0, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_DynamicCast_AsALTF4_Loco_BP_2) == 0x0001C8, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_DynamicCast_AsALTF4_Loco_BP_2' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, K2Node_DynamicCast_bSuccess_2) == 0x0001D0, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Less_DoubleDouble_ReturnValue) == 0x0001D1, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Less_DoubleDouble_ReturnValue_1) == 0x0001D2, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Less_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x0001D8, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy, CallFunc_Less_DoubleDouble_A_ImplicitCast_1) == 0x0001E0, "Member 'BP_Horse_Enemy_C_ExecuteUbergraph_BP_Horse_Enemy::CallFunc_Less_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");

// Function BP_Horse_Enemy.BP_Horse_Enemy_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_Horse_Enemy_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Horse_Enemy_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_Horse_Enemy_C_ReceiveTick");
static_assert(sizeof(BP_Horse_Enemy_C_ReceiveTick) == 0x000004, "Wrong size on BP_Horse_Enemy_C_ReceiveTick");
static_assert(offsetof(BP_Horse_Enemy_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_Horse_Enemy_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

}

