#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Costume_Santa_BP

#include "Basic.hpp"

#include "Costume_Santa_BP_classes.hpp"
#include "Costume_Santa_BP_parameters.hpp"


namespace SDK
{

// Function Costume_Santa_BP.Costume_Santa_BP_C.Costume_TakeOFF
// (BlueprintCallable, BlueprintEvent)

void ACostume_Santa_BP_C::Costume_TakeOFF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Costume_Santa_BP_C", "Costume_TakeOFF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Costume_Santa_BP.Costume_Santa_BP_C.ExecuteUbergraph_Costume_Santa_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACostume_Santa_BP_C::ExecuteUbergraph_Costume_Santa_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Costume_Santa_BP_C", "ExecuteUbergraph_Costume_Santa_BP");

	Params::Costume_Santa_BP_C_ExecuteUbergraph_Costume_Santa_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Costume_Santa_BP.Costume_Santa_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ACostume_Santa_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Costume_Santa_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Costume_Santa_BP.Costume_Santa_BP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACostume_Santa_BP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Costume_Santa_BP_C", "ReceiveTick");

	Params::Costume_Santa_BP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Costume_Santa_BP.Costume_Santa_BP_C.Santa_Effect_OnOff
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ON_                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACostume_Santa_BP_C::Santa_Effect_OnOff(bool ON_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Costume_Santa_BP_C", "Santa_Effect_OnOff");

	Params::Costume_Santa_BP_C_Santa_Effect_OnOff Parms{};

	Parms.ON_ = ON_;

	UObject::ProcessEvent(Func, &Parms);
}

}

