#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EGameUserSettingsFunction

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EGameUserSettingsFunction.EGameUserSettingsFunction
// NumValues: 0x0015
enum class EGameUserSettingsFunction : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator5                           = 5,
	NewEnumerator6                           = 6,
	NewEnumerator7                           = 7,
	NewEnumerator8                           = 8,
	NewEnumerator9                           = 9,
	NewEnumerator10                          = 10,
	NewEnumerator11                          = 11,
	NewEnumerator12                          = 12,
	NewEnumerator13                          = 13,
	NewEnumerator14                          = 14,
	NewEnumerator15                          = 15,
	NewEnumerator16                          = 16,
	NewEnumerator17                          = 17,
	NewEnumerator18                          = 18,
	NewEnumerator20                          = 19,
	EGameUserSettingsFunction_MAX            = 20,
};

}

