#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EMenuInputAction

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EMenuInputAction.EMenuInputAction
// NumValues: 0x0007
enum class EMenuInputAction : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator10                          = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator9                           = 5,
	EMenuInputAction_MAX                     = 6,
};

}

