#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NavFilter_Default

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NavFilter_Default.NavFilter_Default_C
// 0x0000 (0x0048 - 0x0048)
class UNavFilter_Default_C final : public UNavFilter_AIControllerDefault
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NavFilter_Default_C">();
	}
	static class UNavFilter_Default_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNavFilter_Default_C>();
	}
};
static_assert(alignof(UNavFilter_Default_C) == 0x000008, "Wrong alignment on UNavFilter_Default_C");
static_assert(sizeof(UNavFilter_Default_C) == 0x000048, "Wrong size on UNavFilter_Default_C");

}

