#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PDA_TextInputStyle

#include "Basic.hpp"

#include "EColorPalette_structs.hpp"
#include "EFontPalette_structs.hpp"
#include "PDA_WidgetStyle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PDA_TextInputStyle.PDA_TextInputStyle_C
// 0x0028 (0x0060 - 0x0038)
class UPDA_TextInputStyle_C final : public UPDA_WidgetStyle_C
{
public:
	EColorPalette                                 LeftColor;                                         // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 RightColor;                                        // 0x0039(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 TextColor;                                         // 0x003A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 InnerTextColor;                                    // 0x003B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 LeftHighlightColor;                                // 0x003C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 RightHighlightColor;                               // 0x003D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 TextHighlightColor;                                // 0x003E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 InnerTextHighlightColor;                           // 0x003F(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 LeftActiveColor;                                   // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 RightActiveColor;                                  // 0x0041(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 TextActiveColor;                                   // 0x0042(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 InnerTextActiveColor;                              // 0x0043(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 LeftDisabledColor;                                 // 0x0044(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 RightDisabledColor;                                // 0x0045(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 TextDisabledColor;                                 // 0x0046(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EColorPalette                                 InnerTextDisabledColor;                            // 0x0047(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        WidgetHeight;                                      // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CornerRadius;                                      // 0x0050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFontPalette                                  FontStyle;                                         // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFontPalette                                  ValueFontStyle;                                    // 0x0059(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PDA_TextInputStyle_C">();
	}
	static class UPDA_TextInputStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPDA_TextInputStyle_C>();
	}
};
static_assert(alignof(UPDA_TextInputStyle_C) == 0x000008, "Wrong alignment on UPDA_TextInputStyle_C");
static_assert(sizeof(UPDA_TextInputStyle_C) == 0x000060, "Wrong size on UPDA_TextInputStyle_C");
static_assert(offsetof(UPDA_TextInputStyle_C, LeftColor) == 0x000038, "Member 'UPDA_TextInputStyle_C::LeftColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, RightColor) == 0x000039, "Member 'UPDA_TextInputStyle_C::RightColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, TextColor) == 0x00003A, "Member 'UPDA_TextInputStyle_C::TextColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, InnerTextColor) == 0x00003B, "Member 'UPDA_TextInputStyle_C::InnerTextColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, LeftHighlightColor) == 0x00003C, "Member 'UPDA_TextInputStyle_C::LeftHighlightColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, RightHighlightColor) == 0x00003D, "Member 'UPDA_TextInputStyle_C::RightHighlightColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, TextHighlightColor) == 0x00003E, "Member 'UPDA_TextInputStyle_C::TextHighlightColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, InnerTextHighlightColor) == 0x00003F, "Member 'UPDA_TextInputStyle_C::InnerTextHighlightColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, LeftActiveColor) == 0x000040, "Member 'UPDA_TextInputStyle_C::LeftActiveColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, RightActiveColor) == 0x000041, "Member 'UPDA_TextInputStyle_C::RightActiveColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, TextActiveColor) == 0x000042, "Member 'UPDA_TextInputStyle_C::TextActiveColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, InnerTextActiveColor) == 0x000043, "Member 'UPDA_TextInputStyle_C::InnerTextActiveColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, LeftDisabledColor) == 0x000044, "Member 'UPDA_TextInputStyle_C::LeftDisabledColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, RightDisabledColor) == 0x000045, "Member 'UPDA_TextInputStyle_C::RightDisabledColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, TextDisabledColor) == 0x000046, "Member 'UPDA_TextInputStyle_C::TextDisabledColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, InnerTextDisabledColor) == 0x000047, "Member 'UPDA_TextInputStyle_C::InnerTextDisabledColor' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, WidgetHeight) == 0x000048, "Member 'UPDA_TextInputStyle_C::WidgetHeight' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, CornerRadius) == 0x000050, "Member 'UPDA_TextInputStyle_C::CornerRadius' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, FontStyle) == 0x000058, "Member 'UPDA_TextInputStyle_C::FontStyle' has a wrong offset!");
static_assert(offsetof(UPDA_TextInputStyle_C, ValueFontStyle) == 0x000059, "Member 'UPDA_TextInputStyle_C::ValueFontStyle' has a wrong offset!");

}

