#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RollTower_TrapBP

#include "Basic.hpp"

#include "RollTower_TrapBP_classes.hpp"
#include "RollTower_TrapBP_parameters.hpp"


namespace SDK
{

// Function RollTower_TrapBP.RollTower_TrapBP_C.BndEvt__Barrel_Follower_BP_PFPathFollower_K2Node_ComponentBoundEvent_1_ReachedEndSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPFPathFollowerComponent*         FollowerComp                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ARollTower_TrapBP_C::BndEvt__Barrel_Follower_BP_PFPathFollower_K2Node_ComponentBoundEvent_1_ReachedEndSignature__DelegateSignature(class UPFPathFollowerComponent* FollowerComp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "BndEvt__Barrel_Follower_BP_PFPathFollower_K2Node_ComponentBoundEvent_1_ReachedEndSignature__DelegateSignature");

	Params::RollTower_TrapBP_C_BndEvt__Barrel_Follower_BP_PFPathFollower_K2Node_ComponentBoundEvent_1_ReachedEndSignature__DelegateSignature Parms{};

	Parms.FollowerComp = FollowerComp;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RollTower_TrapBP.RollTower_TrapBP_C.BndEvt__RollTower_TrapBP_SM_Tower_Round_02_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FVector                          NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ARollTower_TrapBP_C::BndEvt__RollTower_TrapBP_SM_Tower_Round_02_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "BndEvt__RollTower_TrapBP_SM_Tower_Round_02_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");

	Params::RollTower_TrapBP_C_BndEvt__RollTower_TrapBP_SM_Tower_Round_02_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function RollTower_TrapBP.RollTower_TrapBP_C.ExecuteUbergraph_RollTower_TrapBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ARollTower_TrapBP_C::ExecuteUbergraph_RollTower_TrapBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "ExecuteUbergraph_RollTower_TrapBP");

	Params::RollTower_TrapBP_C_ExecuteUbergraph_RollTower_TrapBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RollTower_TrapBP.RollTower_TrapBP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ARollTower_TrapBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RollTower_TrapBP.RollTower_TrapBP_C.Rol_TL__FinishedFunc
// (BlueprintEvent)

void ARollTower_TrapBP_C::Rol_TL__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "Rol_TL__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RollTower_TrapBP.RollTower_TrapBP_C.Rol_TL__UpdateFunc
// (BlueprintEvent)

void ARollTower_TrapBP_C::Rol_TL__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "Rol_TL__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RollTower_TrapBP.RollTower_TrapBP_C.RollTower_Active
// (BlueprintCallable, BlueprintEvent)

void ARollTower_TrapBP_C::RollTower_Active()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "RollTower_Active");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RollTower_TrapBP.RollTower_TrapBP_C.SpeedUp
// (BlueprintCallable, BlueprintEvent)

void ARollTower_TrapBP_C::SpeedUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "SpeedUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RollTower_TrapBP.RollTower_TrapBP_C.TarzanEnd_Destoy
// (BlueprintCallable, BlueprintEvent)

void ARollTower_TrapBP_C::TarzanEnd_Destoy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "TarzanEnd_Destoy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RollTower_TrapBP.RollTower_TrapBP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ARollTower_TrapBP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollTower_TrapBP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

