#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sign_EndArea_Talk_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Sign_EndArea_Talk_BP.Sign_EndArea_Talk_BP_C.BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35DC[0x3];                                     // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'Sign_EndArea_Talk_BP_C_BndEvt__Sign_EndArea_Talk_BP_Overlap_Check_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function Sign_EndArea_Talk_BP.Sign_EndArea_Talk_BP_C.ExecuteUbergraph_Sign_EndArea_Talk_BP
// 0x0168 (0x0168 - 0x0000)
struct Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35DD[0x3];                                     // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0028(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AALTF4_Loco_BP_C*                       K2Node_DynamicCast_AsALTF4_Loco_BP;                // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35DE[0x3];                                     // 0x0119(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35DF[0x6];                                     // 0x0122(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0128(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UALTF42_GameInstance_C*                 K2Node_DynamicCast_AsALTF42_Game_Instance;         // 0x0140(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetAchievement_ReturnValue;               // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35E0[0x6];                                     // 0x014A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_1;            // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UALTF42_GameInstance_C*                 K2Node_DynamicCast_AsALTF42_Game_Instance_1;       // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0162(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0163(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP) == 0x000008, "Wrong alignment on Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP");
static_assert(sizeof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP) == 0x000168, "Wrong size on Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, EntryPoint) == 0x000000, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, CallFunc_Add_IntInt_ReturnValue) == 0x000004, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000008, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_ComponentBoundEvent_OtherActor) == 0x000010, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_ComponentBoundEvent_OtherComp) == 0x000018, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000020, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_ComponentBoundEvent_bFromSweep) == 0x000024, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_ComponentBoundEvent_SweepResult) == 0x000028, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_DynamicCast_AsALTF4_Loco_BP) == 0x000110, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_DynamicCast_AsALTF4_Loco_BP' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_DynamicCast_bSuccess) == 0x000118, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, CallFunc_Add_IntInt_ReturnValue_1) == 0x00011C, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, CallFunc_Greater_IntInt_ReturnValue) == 0x000120, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, CallFunc_Greater_IntInt_ReturnValue_1) == 0x000121, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, CallFunc_GetPlayerController_ReturnValue) == 0x000128, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, CallFunc_GetPlayerCharacter_ReturnValue) == 0x000130, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::CallFunc_GetPlayerCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, CallFunc_GetGameInstance_ReturnValue) == 0x000138, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_DynamicCast_AsALTF42_Game_Instance) == 0x000140, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_DynamicCast_AsALTF42_Game_Instance' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_DynamicCast_bSuccess_1) == 0x000148, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, CallFunc_SetAchievement_ReturnValue) == 0x000149, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::CallFunc_SetAchievement_ReturnValue' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, CallFunc_GetGameInstance_ReturnValue_1) == 0x000150, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::CallFunc_GetGameInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_DynamicCast_AsALTF42_Game_Instance_1) == 0x000158, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_DynamicCast_AsALTF42_Game_Instance_1' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_DynamicCast_bSuccess_2) == 0x000160, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, Temp_bool_Has_Been_Initd_Variable) == 0x000161, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, Temp_bool_IsClosed_Variable) == 0x000162, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP, K2Node_SwitchInteger_CmpSuccess) == 0x000163, "Member 'Sign_EndArea_Talk_BP_C_ExecuteUbergraph_Sign_EndArea_Talk_BP::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");

}

