#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SM_TeleportCannon_BP

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SM_TeleportCannon_BP.SM_TeleportCannon_BP_C
// 0x0018 (0x02B0 - 0x0298)
class ASM_TeleportCannon_BP_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Cannon_Body;                                       // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USphereComponent*                       Root;                                              // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cannon_Frame;                                      // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SM_TeleportCannon_BP_C">();
	}
	static class ASM_TeleportCannon_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASM_TeleportCannon_BP_C>();
	}
};
static_assert(alignof(ASM_TeleportCannon_BP_C) == 0x000008, "Wrong alignment on ASM_TeleportCannon_BP_C");
static_assert(sizeof(ASM_TeleportCannon_BP_C) == 0x0002B0, "Wrong size on ASM_TeleportCannon_BP_C");
static_assert(offsetof(ASM_TeleportCannon_BP_C, Cannon_Body) == 0x000298, "Member 'ASM_TeleportCannon_BP_C::Cannon_Body' has a wrong offset!");
static_assert(offsetof(ASM_TeleportCannon_BP_C, Root) == 0x0002A0, "Member 'ASM_TeleportCannon_BP_C::Root' has a wrong offset!");
static_assert(offsetof(ASM_TeleportCannon_BP_C, Cannon_Frame) == 0x0002A8, "Member 'ASM_TeleportCannon_BP_C::Cannon_Frame' has a wrong offset!");

}

