#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TarzanArea_InCheck_BP

#include "Basic.hpp"

#include "TarzanArea_InCheck_BP_classes.hpp"
#include "TarzanArea_InCheck_BP_parameters.hpp"


namespace SDK
{

// Function TarzanArea_InCheck_BP.TarzanArea_InCheck_BP_C.AreaSave_DeActivate
// (BlueprintCallable, BlueprintEvent)

void ATarzanArea_InCheck_BP_C::AreaSave_DeActivate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TarzanArea_InCheck_BP_C", "AreaSave_DeActivate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TarzanArea_InCheck_BP.TarzanArea_InCheck_BP_C.CheckTL__FinishedFunc
// (BlueprintEvent)

void ATarzanArea_InCheck_BP_C::CheckTL__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TarzanArea_InCheck_BP_C", "CheckTL__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TarzanArea_InCheck_BP.TarzanArea_InCheck_BP_C.CheckTL__InCheck_Event__EventFunc
// (BlueprintEvent)

void ATarzanArea_InCheck_BP_C::CheckTL__InCheck_Event__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TarzanArea_InCheck_BP_C", "CheckTL__InCheck_Event__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TarzanArea_InCheck_BP.TarzanArea_InCheck_BP_C.CheckTL__UpdateFunc
// (BlueprintEvent)

void ATarzanArea_InCheck_BP_C::CheckTL__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TarzanArea_InCheck_BP_C", "CheckTL__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TarzanArea_InCheck_BP.TarzanArea_InCheck_BP_C.ExecuteUbergraph_TarzanArea_InCheck_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATarzanArea_InCheck_BP_C::ExecuteUbergraph_TarzanArea_InCheck_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TarzanArea_InCheck_BP_C", "ExecuteUbergraph_TarzanArea_InCheck_BP");

	Params::TarzanArea_InCheck_BP_C_ExecuteUbergraph_TarzanArea_InCheck_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TarzanArea_InCheck_BP.TarzanArea_InCheck_BP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ATarzanArea_InCheck_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TarzanArea_InCheck_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

