#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UnlockLocation_BP

#include "Basic.hpp"

#include "UnlockLocation_BP_classes.hpp"
#include "UnlockLocation_BP_parameters.hpp"


namespace SDK
{

// Function UnlockLocation_BP.UnlockLocation_BP_C.Ballon_Bomb_Event
// (BlueprintCallable, BlueprintEvent)

void AUnlockLocation_BP_C::Ballon_Bomb_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockLocation_BP_C", "Ballon_Bomb_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UnlockLocation_BP.UnlockLocation_BP_C.BndEvt__UnlockLocation_BP_Target_Ballon_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FVector                          NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AUnlockLocation_BP_C::BndEvt__UnlockLocation_BP_Target_Ballon_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockLocation_BP_C", "BndEvt__UnlockLocation_BP_Target_Ballon_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature");

	Params::UnlockLocation_BP_C_BndEvt__UnlockLocation_BP_Target_Ballon_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UnlockLocation_BP.UnlockLocation_BP_C.Char_CannonFire_Event
// (BlueprintCallable, BlueprintEvent)

void AUnlockLocation_BP_C::Char_CannonFire_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockLocation_BP_C", "Char_CannonFire_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UnlockLocation_BP.UnlockLocation_BP_C.Drop_TL__FinishedFunc
// (BlueprintEvent)

void AUnlockLocation_BP_C::Drop_TL__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockLocation_BP_C", "Drop_TL__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UnlockLocation_BP.UnlockLocation_BP_C.Drop_TL__UpdateFunc
// (BlueprintEvent)

void AUnlockLocation_BP_C::Drop_TL__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockLocation_BP_C", "Drop_TL__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UnlockLocation_BP.UnlockLocation_BP_C.ExecuteUbergraph_UnlockLocation_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUnlockLocation_BP_C::ExecuteUbergraph_UnlockLocation_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockLocation_BP_C", "ExecuteUbergraph_UnlockLocation_BP");

	Params::UnlockLocation_BP_C_ExecuteUbergraph_UnlockLocation_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UnlockLocation_BP.UnlockLocation_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AUnlockLocation_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockLocation_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UnlockLocation_BP.UnlockLocation_BP_C.Test Loction Swap
// (BlueprintCallable, BlueprintEvent)

void AUnlockLocation_BP_C::Test_Loction_Swap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockLocation_BP_C", "Test Loction Swap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UnlockLocation_BP.UnlockLocation_BP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AUnlockLocation_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockLocation_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

