#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuBackground_Silence

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WBP_MenuBackground_Silence.WBP_MenuBackground_Silence_C.SetBackgroundVisuals
// 0x0014 (0x0014 - 0x0000)
struct WBP_MenuBackground_Silence_C_SetBackgroundVisuals final
{
public:
	struct FLinearColor                           BackgroundColor;                                   // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BackgroundBlurStrength;                            // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MenuBackground_Silence_C_SetBackgroundVisuals) == 0x000004, "Wrong alignment on WBP_MenuBackground_Silence_C_SetBackgroundVisuals");
static_assert(sizeof(WBP_MenuBackground_Silence_C_SetBackgroundVisuals) == 0x000014, "Wrong size on WBP_MenuBackground_Silence_C_SetBackgroundVisuals");
static_assert(offsetof(WBP_MenuBackground_Silence_C_SetBackgroundVisuals, BackgroundColor) == 0x000000, "Member 'WBP_MenuBackground_Silence_C_SetBackgroundVisuals::BackgroundColor' has a wrong offset!");
static_assert(offsetof(WBP_MenuBackground_Silence_C_SetBackgroundVisuals, BackgroundBlurStrength) == 0x000010, "Member 'WBP_MenuBackground_Silence_C_SetBackgroundVisuals::BackgroundBlurStrength' has a wrong offset!");

// Function WBP_MenuBackground_Silence.WBP_MenuBackground_Silence_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_MenuBackground_Silence_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MenuBackground_Silence_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_MenuBackground_Silence_C_PreConstruct");
static_assert(sizeof(WBP_MenuBackground_Silence_C_PreConstruct) == 0x000001, "Wrong size on WBP_MenuBackground_Silence_C_PreConstruct");
static_assert(offsetof(WBP_MenuBackground_Silence_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_MenuBackground_Silence_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_MenuBackground_Silence.WBP_MenuBackground_Silence_C.ExecuteUbergraph_WBP_MenuBackground_Silence
// 0x001C (0x001C - 0x0000)
struct WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3064[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_GetColorByName_Color;                     // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetBackgroundVisuals_BackgroundBlurStrength_ImplicitCast; // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence) == 0x000004, "Wrong alignment on WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence");
static_assert(sizeof(WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence) == 0x00001C, "Wrong size on WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence");
static_assert(offsetof(WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence, EntryPoint) == 0x000000, "Member 'WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence, K2Node_Event_IsDesignTime) == 0x000004, "Member 'WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence, CallFunc_GetColorByName_Color) == 0x000008, "Member 'WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence::CallFunc_GetColorByName_Color' has a wrong offset!");
static_assert(offsetof(WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence, CallFunc_SetBackgroundVisuals_BackgroundBlurStrength_ImplicitCast) == 0x000018, "Member 'WBP_MenuBackground_Silence_C_ExecuteUbergraph_WBP_MenuBackground_Silence::CallFunc_SetBackgroundVisuals_BackgroundBlurStrength_ImplicitCast' has a wrong offset!");

}

