#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: YouDied_Widget

#include "Basic.hpp"


namespace SDK::Params
{

// Function YouDied_Widget.YouDied_Widget_C.ExecuteUbergraph_YouDied_Widget
// 0x0028 (0x0028 - 0x0000)
struct YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3588[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue;         // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3589[0x4];                                     // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget) == 0x000008, "Wrong alignment on YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget");
static_assert(sizeof(YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget) == 0x000028, "Wrong size on YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget");
static_assert(offsetof(YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget, EntryPoint) == 0x000000, "Member 'YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget::EntryPoint' has a wrong offset!");
static_assert(offsetof(YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget, CallFunc_PlayAnimation_ReturnValue_1) == 0x000010, "Member 'YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget, CallFunc_RandomIntegerInRange_ReturnValue) == 0x000018, "Member 'YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget::CallFunc_RandomIntegerInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget, CallFunc_Array_Get_Item) == 0x000020, "Member 'YouDied_Widget_C_ExecuteUbergraph_YouDied_Widget::CallFunc_Array_Get_Item' has a wrong offset!");

}

